/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.DuAn1.FormAn;

import com.DuAn1.ChartAn.ModelChart;
import java.awt.Color;

/**
 *
 * @author trana
 */
public class Form extends javax.swing.JPanel {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        setOpaque(false);
        init();
       
    }

    private void init() {
        chart.addLegend("Iphone", new Color(12, 84, 175), new Color(0, 108, 247));
        chart.addLegend("Samsung", new Color(54, 4, 143), new Color(104, 49, 200));
        chart.addLegend("Sony", new Color(5, 125, 0), new Color(95, 209, 69));
        chart.addData(new ModelChart("Tháng 1", new double[]{500, 200, 80, 89}));
        chart.addData(new ModelChart("Tháng 2", new double[]{600, 750, 90, 150}));
        chart.addData(new ModelChart("Tháng 3", new double[]{300, 400, 85, 189}));
        chart.addData(new ModelChart("Tháng 4", new double[]{100, 290, 980, 189}));
        chart.addData(new ModelChart("Tháng 5", new double[]{500, 200, 180, 189}));
        chart.addData(new ModelChart("Tháng 6", new double[]{500, 200, 80, 89}));
        chart.addData(new ModelChart("Tháng 7", new double[]{600, 750, 90, 150}));
        chart.addData(new ModelChart("Tháng 8", new double[]{300, 480, 851, 119}));
//        chart.addData(new ModelChart("Tháng 9", new double[]{520, 220, 980, 189}));
//        chart.addData(new ModelChart("Tháng 10", new double[]{520, 220, 180, 189}));
//        chart.addData(new ModelChart("Tháng 11", new double[]{590, 240, 80, 89}));
//        chart.addData(new ModelChart("Tháng 12", new double[]{123, 750, 90, 150}));

        chart.start();
//        lineChart.addLegend("ND1", new Color(12, 84, 175), new Color(0, 108, 247));
//        lineChart.addLegend("ND2", new Color(54, 4, 143), new Color(104, 49, 200));
//        lineChart.addLegend("ND3", new Color(5, 125, 0), new Color(95, 209, 69));
//        lineChart.addData(new ModelChart("Tháng 1", new double[]{500, 200, 80, 89}));
//        lineChart.addData(new ModelChart("Tháng 2", new double[]{600, 750, 90, 150}));
//        lineChart.addData(new ModelChart("Tháng 3", new double[]{300, 400, 85, 189}));
//        lineChart.addData(new ModelChart("Tháng 4", new double[]{100, 290, 980, 189}));
//        lineChart.addData(new ModelChart("Tháng 5", new double[]{500, 200, 180, 189}));
//        lineChart.start();
//        progress1.start();
//        progress2.start();
//        progress3.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new com.DuAn1.SwingAn.RoundPanel();
        roundPanel4 = new com.DuAn1.SwingAn.RoundPanel();
        roundPanel5 = new com.DuAn1.SwingAn.RoundPanel();
        chart = new com.DuAn1.ChartAn.Chart();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        roundPanel4.setBackground(new java.awt.Color(0, 51, 51));
        roundPanel4.setLayout(new java.awt.BorderLayout());

        roundPanel5.setBackground(new java.awt.Color(0, 51, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Số lượng sản phẩm nhập từng tháng");

        javax.swing.GroupLayout roundPanel5Layout = new javax.swing.GroupLayout(roundPanel5);
        roundPanel5.setLayout(roundPanel5Layout);
        roundPanel5Layout.setHorizontalGroup(
            roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(roundPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        roundPanel5Layout.setVerticalGroup(
            roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chart, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGap(560, 560, 560)
                        .addComponent(roundPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
                    .addComponent(roundPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addComponent(roundPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(roundPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.DuAn1.ChartAn.Chart chart;
    private javax.swing.JLabel jLabel2;
    private com.DuAn1.SwingAn.RoundPanel roundPanel1;
    private com.DuAn1.SwingAn.RoundPanel roundPanel4;
    private com.DuAn1.SwingAn.RoundPanel roundPanel5;
    // End of variables declaration//GEN-END:variables
}
