/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.DuAn1.test;

import com.DuAn1.Dao.SanPhamDAO;
import com.DuAn1.Helper.ShareHelper;
import com.DuAn1.Model.SanPhamModel;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author RAVEN
 */
public class Slide3 extends javax.swing.JPanel {

    /**
     * Creates new form Slide1
     */
    SanPhamDAO daoSP = new SanPhamDAO();

    public Slide3() {
        initComponents();

        List<SanPhamModel> list = daoSP.selectTop3();
        int i = 0;
        for (SanPhamModel sanPhamModel : list) {
            if (i == 2) {
                if (sanPhamModel.getHinh() != null) {
                    pictureBox1.setImage(ShareHelper.readLogo(sanPhamModel.getHinh().trim()));
                    txtTenSP.setText(sanPhamModel.getTenSP());
                    break;
                }

            }
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pictureBox1 = new swing.PictureBox_1();
        txtTenSP = new javax.swing.JLabel();

        pictureBox1.setImage(new javax.swing.ImageIcon(getClass().getResource("/Images/Xiaomi.jpg"))); // NOI18N

        txtTenSP.setFont(new java.awt.Font("sansserif", 1, 40)); // NOI18N
        txtTenSP.setForeground(new java.awt.Color(255, 0, 0));
        txtTenSP.setText("Iphone 14");
        pictureBox1.add(txtTenSP);
        txtTenSP.setBounds(0, 0, 350, 52);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pictureBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pictureBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.PictureBox_1 pictureBox1;
    private javax.swing.JLabel txtTenSP;
    // End of variables declaration//GEN-END:variables
}
