CREATE DATABASE CUAHANG_DT
GO
USE CUAHANG_DT
GO

CREATE TABLE VAITRO(
	MaVaiTrO CHAR(10) PRIMARY KEY,
	ChucVu NVARCHAR(20) NOT NULL,
	GhiChu TEXT
)
CREATE TABLE NHANVIEN(
	MaNV CHAR(10) PRIMARY KEY,
	HoTen NVARCHAR(50) NOT NULL,
	NgaySinh DATE NOT NULL,
	GioiTinh BIT NOT NULL,
	DiaChi NVARCHAR(50) NOT NULL,
	SDT CHAR(15) NOT NULL UNIQUE,
	Email CHAR(50) NOT NULL UNIQUE,
	MatKhau CHAR(50) NOT NULL,
	MaVaiTro CHAR(10) NOT NULL,
	Hinh CHAR(100) NOT NULL,
	FOREIGN KEY (MaVaiTro) REFERENCES VAITRO(MaVaiTro) ON DELETE NO ACTION ON UPDATE CASCADE
)
CREATE TABLE LUONG(
	MaLuong CHAR(10) PRIMARY KEY,
	SoNgayLam FLOAT NOT NULL,
	LuongCoBan MONEY NOT NULL,
	NgayVaoCTY DATE NOT NULL,
	SoGioTangCa FLOAT,
	LuongTangCa MONEY,
	KhoangTru MONEY,
	TongTien MONEY NOT NULL,
	TrangThai BIT NOT NULL,
	MaNV CHAR(10) NOT NULL,
	FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV) ON DELETE NO ACTION ON UPDATE CASCADE
)
CREATE TABLE GIAMGIA(
	MaGiamGia CHAR(10) PRIMARY KEY,
	NgayBD DATETIME NOT NULL,
	NgayKT DATETIME NOT NULL,
	PhanTram FLOAT NOT NULL,
	MoTa TEXT,
	TrangThai BIT NOT NULL,
	MaNV CHAR(10) NOT NULL,
	FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV) ON DELETE NO ACTION ON UPDATE CASCADE
)
CREATE TABLE KHACHHANG(
	MaKH CHAR(10) PRIMARY KEY,
	TenKH NVARCHAR(50) NOT NULL,
	SDT CHAR(15) NOT NULL UNIQUE,
	NgaySinh DATE NOT NULL,
	DiaChi NVARCHAR(50) NOT NULL,
	GioiTinh BIT NOT NULL,
	LoaiKH NVARCHAR(20) NOT NULL,
	TrangThai BIT NOT NULL,
	MoTa TEXT,
	MaNV CHAR(10) NOT NULL,
	Hinh CHAR(100) NOT NULL,
	FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV) ON DELETE NO ACTION ON UPDATE CASCADE
)
CREATE TABLE LICHSU(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ThoiGianThem DATETIME,
	ThoiGianSua DATETIME,
	ThoiGianXoa DATETIME,
	ThoiGianHoatDong DATETIME NOT NULL,
	BangThaoTac NVARCHAR(50) NOT NULL,
	MaNV CHAR(10) NOT NULL,
	FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV) ON DELETE NO ACTION ON UPDATE CASCADE
)
CREATE TABLE SANPHAM(
	MaSP CHAR(10) PRIMARY KEY,
	TenSP NVARCHAR(50) NOT NULL,
	MAU NVARCHAR(20) NOT NULL,
	Gia MONEY NOT NULL,
	LoaiSP NVARCHAR(30) NOT NULL,
	NgayNhap DATETIME NOT NULL,
	NoiNhap NVARCHAR(50) NOT NULL,
	SoLuong INT NOT NULL,
	TrangThai BIT NOT NULL,
	Hinh CHAR(100) NOT NULL,
	MaNV CHAR(10) NOT NULL,
	MaGiamGia CHAR(10) NOT NULL,
	MaDT CHAR(10) NOT NULL,
	FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV) ON DELETE NO ACTION ON UPDATE CASCADE
	
)
CREATE TABLE DIENTHOAI(
	MaDT CHAR(10) PRIMARY KEY,
	CPU CHAR(20) NOT NULL,
	MangHinh CHAR(20) NOT NULL,
	BoNho CHAR(10) NOT NULL,
	MoTa TEXT,
	MaSP CHAR(10) NOT NULL,
	CAMERA CHAR(20) NOT NULL,
	Pin CHAR(10) NOT NULL,
	RAM CHAR(10) NOT NULL,
	FOREIGN KEY (MaDT) REFERENCES SANPHAM(MaSP) ON DELETE NO ACTION ON UPDATE CASCADE
)

CREATE TABLE HOADON(
	MaHD CHAR(10) PRIMARY KEY,
	TenSP NVARCHAR(50) NOT NULL,
	SoLuong INT NOT NULL,
	TrangThai BIT NOT NULL,
	DonGia MONEY NOT NULL,
	TongTien MONEY NOT NULL,
	Thue FLOAT,
	NgayXuat DATETIME NOT NULL,
	MoTa TEXT,
	TenCTY NVARCHAR(50) NOT NULL,
	MaNV CHAR(10) NOT NULL,
	FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV) ON DELETE NO ACTION ON UPDATE CASCADE
)
CREATE TABLE HOADONCT(
	MaHDCT INT IDENTITY(1,1) PRIMARY KEY,
	MaSP CHAR(10) NOT NULL,
	SoLuong INT NOT NULL,
	MaHD CHAR(10) NOT NULL,
	FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD) ON DELETE NO ACTION ON UPDATE CASCADE
)
CREATE TABLE BAOHANH(
	MaBH CHAR(10) PRIMARY KEY,
	MaHD CHAR(10) NOT NULL,
	SoIMEI CHAR(15) NOT NULL,
	NgayBH DATETIME NOT NULL,
	NgayHetHan DATETIME NOT NULL,
	GhiChu TEXT,
	MaKH CHAR(10) NOT NULL,
	FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH) ON DELETE NO ACTION ON UPDATE CASCADE
)
CREATE TABLE DATSP(
	MaDH CHAR(10) PRIMARY KEY,
	SoLuong INT NOT NULL,
	SDT CHAR(15) NOT NULL UNIQUE,
	TrangThai BIT NOT NULL,
	DonGia MONEY NOT NULL,
	TongTien MONEY NOT NULL,
	Thue FLOAT,
	MaNV CHAR(10) NOT NULL,
	FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV) ON DELETE NO ACTION ON UPDATE CASCADE
)
CREATE TABLE DATSPCT(
	MaDatCT INT IDENTITY(1,1) PRIMARY KEY,
	SoLuong INT NOT NULL,
	MaDH CHAR(10) NOT NULL,
	MaSP CHAR(10) NOT NULL,
	FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP) ON DELETE NO ACTION ON UPDATE CASCADE,
	FOREIGN KEY (MaDH) REFERENCES DATSP(MaDH) ON DELETE NO ACTION ON UPDATE NO ACTION

)

